### ISSUE TITLE
dht.findprovs() throwing NPE

### ISSUE THREAD

**Issue by Hazae41** [ipfs/java-ipfs-http-client#106]
With the official API
http://localhost:5001/api/v0/dht/findprovs?arg=QmRyeA1xCjreUgbSCc4QLhYzfRnnPGyfQTMuxpf6kUYXoX
```
{"Extra":"","ID":"QmVJdTE4uLdD1JGysYRzf9FCHNkJdvWGeEKWtmk9Zk5KWG","Responses":null,"Type":6}
{"Extra":"","ID":"QmWCsxqpvYMKCeCejvXLc7TbWrraLwmAKMxWgcsKQ8xUL3","Responses":null,"Type":6}
{"Extra":"","ID":"QmdDKtQ2Z34VG38m8w6H3cUqqttN69E9SENgQPgDnBPXpC","Responses":null,"Type":6}
{"Extra":"","ID":"QmVJdTE4uLdD1JGysYRzf9FCHNkJdvWGeEKWtmk9Zk5KWG","Responses":null,"Type":0}
{"Extra":"","ID":"QmWCsxqpvYMKCeCejvXLc7TbWrraLwmAKMxWgcsKQ8xUL3","Responses":null,"Type":0}
{"Extra":"","ID":"QmdDKtQ2Z34VG38m8w6H3cUqqttN69E9SENgQPgDnBPXpC","Responses":null,"Type":0}
...
```

With java-ipfs-api
```
> ipfs.dht.findprovs("QmRyeA1xCjreUgbSCc4QLhYzfRnnPGyfQTMuxpf6kUYXoX")
{Extra=, ID=QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ, Responses=null, Type=6}
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at io.ipfs.api.IPFS.readFully(IPFS.java:722)
        at io.ipfs.api.IPFS.get(IPFS.java:660)
        at io.ipfs.api.IPFS.retrieve(IPFS.java:640)
        at io.ipfs.api.IPFS.retrieveAndParse(IPFS.java:602)
        at io.ipfs.api.IPFS.retrieveMap(IPFS.java:598)
        at io.ipfs.api.IPFS.access$200(IPFS.java:15)
        at io.ipfs.api.IPFS$DHT.findprovs(IPFS.java:403)

```

**Comment by ianopolous** [comment]
Thanks for the report. This should be fixed in the latest master, please reopen if not.
