### ISSUE TITLE
IPFS.add() uses java.nio.file.Paths?

### ISSUE THREAD

**Issue by IordacheClaudiu** [ipfs/java-ipfs-http-client#131]
I'm trying to run this client library on an Android 7 (API Level 24) and I receive this exception:
```
W/System.err: java.lang.NoClassDefFoundError:  Failed resolution of: Ljava/nio/file/Paths; 
at io.ipfs.api.IPFS.add(IPFS.java:95)
at io.ipfs.api.IPFS.add(IPFS.java:86)
at io.ipfs.api.IPFS.add(IPFS.java:82)
```

**Comment by ianopolous** [comment]
This is only meant to run on the JVM. Android is incompatible with standard Java.
